apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: test-alert
  namespace: monitoring
spec:
  groups:
  - name: test.rules
    rules:
    - alert: TestEmailAlert
      expr: vector(1)
      for: 1m
      labels:
        severity: warning
      annotations:
        summary: "Kobie Test Alert"
        description: "This is a test email from Alertmanager."
