frontend:
  image:
    repository: ghcr.io/vaishjp/frontend
    tag: "9ae6cb0-2"
  replicas: 2
  service:
    type: ClusterIP
    port: 80
    targetPort: 3000
backend:
  image:
    repository: ghcr.io/vaishjp/backend
    tag: "9ae6cb0-2"
  replicas: 2
  service:
    type: ClusterIP
    port: 4000
  env:
    port: "4000"
    corsOrigin: "http://localhost:3000"
    jwtExpiresIn: "12h"
    allowedEmailDomains: "pesu.pes.edu,kobie.com"
    otpTtlMinutes: "10"
    pgPort: "5432"
    pgDatabase: "postgres"
    pgSsl: "false"
    smtpHost: "smtp.gmail.com"
    smtpPort: "587"
    smtpSecure: "false"
    smtpFrom: "vaishjp2005@gmail.com"
    githubBranch: "local-demo"
    githubAlertsDir: "apps/alerting"